CREATE TABLE 'users' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'username' TEXT(15) DEFAULT NULL,
'email' TEXT(25) DEFAULT NULL,
'password' TEXT DEFAULT NULL
);

CREATE TABLE 'sites' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'sitename' TEXT DEFAULT NULL,
'url' TEXT DEFAULT NULL,
'favicon_url' TEXT DEFAULT NULL
);

CREATE TABLE 'lists' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'id_users' INTEGER DEFAULT NULL REFERENCES 'users' ('id'),
'name' TEXT DEFAULT NULL,
'description' TEXT DEFAULT NULL,
'time_submitted' TEXT DEFAULT NULL
);

CREATE TABLE 'lists_sites' (
'id' INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
'id_sites' INTEGER DEFAULT NULL REFERENCES 'sites' ('id'),
'id_lists' INTEGER DEFAULT NULL REFERENCES 'lists' ('id')
);